# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# Exclude files in html/ directory
exclude: '^html/'

repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
      - id: tflint
        args:
          - "--module"
          - "--config=.tflint.hcl"

  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0"
    hooks:
      - id: terraform-docs-go
        args: ["markdown", "table", "--output-file", "README.md", "./terraform"]

  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.62.3
    hooks:
      - id: terraform_tfsec